apiVersion: asserts.grafana.crossplane.io/v1alpha1
kind: ProfileConfig
metadata:
  annotations:
    meta.upbound.io/example-id: asserts/v1alpha1/profileconfig
  labels:
    testing.upbound.io/example-name: production
  name: production
spec:
  forProvider:
    dataSourceUid: grafanacloud-profiles
    defaultConfig: false
    entityPropertyToProfileLabelMapping:
      cluster: k8s_cluster_name
      container: k8s_container_name
      namespace: k8s_namespace_name
      otel_namespace: service_namespace
      otel_service: service_name
    match:
    - op: =
      property: asserts_entity_type
      values:
      - Service
    - op: =
      property: deployment_environment
      values:
      - production
      - staging
    - op: =
      property: asserts_site
      values:
      - us-east-1
      - us-west-2
    name: production
    priority: 1000
