apiVersion: asserts.grafana.m.crossplane.io/v1alpha1
kind: LogConfig
metadata:
  annotations:
    meta.upbound.io/example-id: asserts/v1alpha1/logconfig
  labels:
    testing.upbound.io/example-name: production
  name: production
  namespace: upbound-system
spec:
  forProvider:
    dataSourceUid: grafanacloud-logs
    defaultConfig: false
    entityPropertyToLogLabelMapping:
      environment: env
      otel_namespace: service_namespace
      otel_service: service_name
      site: region
    errorLabel: error
    filterBySpanId: true
    filterByTraceId: true
    match:
    - op: =
      property: asserts_entity_type
      values:
      - Service
    - op: =
      property: environment
      values:
      - production
      - staging
    - op: =
      property: site
      values:
      - us-east-1
      - us-west-2
    name: production
    priority: 1000
